version: '3' 

services: 
  nginx:
    container_name: nginx
    image: nginx:1.14.0
    network_mode: host
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/api.conf:/etc/nginx/conf.d/api.conf

  mysql: 
    image: mysql:5.7 
    ports: 
      - 3306:3306
    volumes: 
      - ./.data/mysql/data:/var/lib/mysql:rw
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    container_name: mysql
    network_mode: host
    restart: always
    command:
      - mysqld
      - --default-time-zone=Asia/Shanghai
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

